import re
import json

def parse_ai_services(text_blob):
    services = []

    # Primary Regex:
    # Attempts to match well-structured URLs or common placeholders in brackets/parentheses.
    # - Name: `(?P<name>.+?)` (non-greedy)
    # - URL patterns:
    #   1. HTTP(S) URLs, possibly comma-separated: `(?:(?:https?://|www\.)[^\s,\"']+(?:\s*,\s*(?:https?://|www\.)[^\s,\"']+)*)`
    #   2. Placeholders in parentheses: `(?:\([^)]+\))` (e.g., "(Integrated into macOS)")
    #   3. Placeholders in square brackets: `(?:\[[^\]]+\])` (e.g., "[suspicious link removed]")
    # - Category Description: `(?P<category_description>.+)` (greedy for the rest)
    # If a line doesn't match this, it means the URL part is not one of these common forms,
    # or the name/structure is complex. It will then fall to the rsplit logic.
    primary_regex = re.compile(
        r"^(?P<name>.+?)\s*-\s*"
        r"(?P<url>"
        r"(?:(?:https?://|www\.)[^\s,\"']+(?:\s*,\s*(?:https?://|www\.)[^\s,\"']+)*)"  # HTTP(S) URLs
        r"|"
        r"(?:\([^)]+\))"  # Placeholders in parentheses
        r"|"
        r"(?:\[[^\]]+\])"  # Placeholders in square brackets
        r")\s*-\s*"
        r"(?P<category_description>.+)$"
    )

    lines = text_blob.split('\n')

    for line in lines:
        line = line.strip()
        if not line:
            continue

        # Ignore delimiters and headers explicitly
        if line.lower().startswith("okay next chunk") or \
           line.lower().startswith("okay, here's the next chunk") or \
           line.lower().startswith("hyper-niche generative ai") or \
           line.lower().startswith("ai for very niche scientific & engineering tools:") or \
           line.lower().startswith("ai for niche industrial & automation applications:") or \
           line.lower().startswith("ai for very specific data & mlops tasks:") or \
           line.lower().startswith("ai for niche business & public sector solutions:") or \
           line.lower().startswith("do not remove any services!") or \
           line.lower().startswith("starting now, here is the first chunk"):
            continue

        match = primary_regex.match(line)

        if match:
            service_info = match.groupdict()
            name = service_info["name"].strip()
            url = service_info["url"].strip()
            category = service_info["category_description"].strip()
            services.append({"name": name, "url": url, "category_description": category})
        elif line.count(" - ") >= 2:
            # Fallback: Split by the last two occurrences of " - "
            # This is robust for cases where the name might contain " - "
            # e.g. "Complex Name - Part 2 - URL - Description"
            parts = line.rsplit(" - ", 2)
            # parts will be [name_candidate, url_candidate, description_candidate]
            name = parts[0].strip()
            url = parts[1].strip()
            category = parts[2].strip()
            services.append({"name": name, "url": url, "category_description": category})
        else:
            # If not enough " - " separators for rsplit, it's likely a header or malformed
            print(f"Skipping line (no primary regex match, not enough ' - ' for rsplit): {line}")

    return json.dumps(services, indent=2)

if __name__ == '__main__':
    input_text = """DO NOT REMOVE ANY SERVICES! Can you add to the closest fitting catagory per link, any and all missing services form this list that I may not have: Starting now, here is the first chunk of the Unified AI Services List (A-B):

3Play Media - https://www.3playmedia.com/ - Media AI (AI for transcription and captioning)
Acelab - https://acelab.ai/ - Construction AI (AI for material specification and product discovery in architecture & construction)
accessiBe - https://accessibe.com/ - Accessibility AI (AI for Website ADA/WCAG Compliance)
AccuWeather For Business (SkyGuard AI) - https://www.accuweather.com/business/skyguard - Weather AI (AI for hyper-local severe weather warnings and business impact prediction)
Accentize (AI Audio Plugins) - https://www.accentize.com/ - Audio AI (AI plugins for audio restoration, noise reduction, and de-reverberation for professional audio)
Adobe Acrobat (AI Assistant) - https://www.adobe.com/acrobat/ai-assistant.html - Productivity AI (AI for summarizing PDFs, answering questions, and generating insights from documents)
Adobe Experience Platform AI Services - https://experience.adobe.com/solutions/experience-platform/services.html - Marketing/Customer Experience AI (AI for customer journey analytics, personalization, and audience segmentation)
Adobe Express (AI features) - https://www.adobe.com/express/ - Creative AI (AI for quick content creation, text-to-image, text effects, and video generation for social media)
Adobe Firefly - https://www.adobe.com/sensei/generative-ai/firefly.html - Generative AI (Generative AI for Creative Cloud apps (image generation, effects))
Adobe Frame.io (AI features) - https://www.adobe.com/products/video/frame-io/features.html - Video Production AI (AI for automated transcription, content tagging, and project management in video workflows)
Adobe Sensei (embedded in Creative Cloud) - https://www.adobe.com/sensei.html - Creative AI (Underlying AI/ML framework powering intelligent features across Adobe products)
AeroVironment (Quantix Mapper) - https://www.avinc.com/uas/quantix-mapper/ - Agriculture/Environmental AI (AI-powered drone for agricultural and environmental mapping)
Aible - https://www.aible.com/ - Business AI (Enterprise AI for analytics, GenAI for business impact)
Aiberry - https://www.aiberry.com/ - Healthcare AI (Mental Health Screening)
AI.builders - https://ai.builders/ - Construction AI (AI for automating construction planning, scheduling, and risk assessment)
AI Tools Directory (AITools.fyi) - https://aitools.fyi/ - AI Tool Directory (Comprehensive directory of AI tools)
AIVA - https://www.aiva.ai/ - Generative AI (AI for Music Composition)
Alation (Data Intelligence Platform) - https://www.alation.com/ - Data Governance AI (AI for data cataloging, search, and governance)
Algolia (AI features) - https://www.algolia.com/ - Search AI (AI-powered search and discovery for websites and apps)
Alteryx AI Platform - https://www.alteryx.com/products/alteryx-ai-platform - Machine Learning Platforms (Low-code/no-code analytics and data science platform with AI)
Amazon.com (Recommendation Engine) - https://www.amazon.com/ - E-commerce AI (AI for personalized product recommendations)
Amazon Alexa - https://www.amazon.com/alexa - Conversational AI/Smart Home AI (Amazon's voice assistant)
Amazon CodeCatalyst (AI features) - https://aws.amazon.com/codecatalyst/ - Developer AI (Unified software development service with AI-powered code suggestions and workflow automation)
Amazon CodeWhisperer - https://aws.amazon.com/codewhisperer/ - Generative AI (Generative AI coding assistant with real-time suggestions)
Amazon Comprehend - https://aws.amazon.com/comprehend/ - Large Language Models (LLMs) & Conversational AI (Extracts meaning from text)
Amazon DeepComposer - https://aws.amazon.com/deepcomposer/ - Generative Music AI (AI-powered keyboard for composing music using generative AI)
Amazon DeepRacer - https://aws.amazon.com/deepracer/ - Reinforcement Learning AI (AI-powered 1/18th scale race car for learning reinforcement learning)
Amazon Fraud Detector - https://aws.amazon.com/fraud-detector/ - Fraud Prevention AI (AI for building, training, and deploying ML models to detect online fraud)
Amazon Go Stores (Just Walk Out Technology) - https://www.amazon.com/b?node=16008589011 - Retail AI (AI for computer vision and sensor fusion to enable cashier-less shopping)
Amazon HealthScribe - https://aws.amazon.com/blogs/aws/now-generally-available-aws-healthscribe/ - Healthcare AI (AI service for transcribing and structuring clinical conversations)
Amazon Kinesis Video Streams with Rekognition Video - https://aws.amazon.com/kinesis/video-streams/integrations/rekognition-video/ - Video Analytics AI (AI for real-time video analytics)
Amazon Lex - https://aws.amazon.com/lex/ - Large Language Models (LLMs) & Conversational AI (Conversational AI platform for building chatbots)
Amazon Lookout for Equipment - https://aws.amazon.com/lookout-for-equipment/ - Industrial AI (AI for predictive maintenance for industrial equipment)
Amazon Lookout for Metrics - https://aws.amazon.com/lookout-for-metrics/ - Business Analytics AI (AI for automatically detecting anomalies in business and operational data)
Amazon Monitron - https://aws.amazon.com/monitron/ - Industrial AI (End-to-end system for predictive maintenance of industrial machinery)
Amazon Prime Video / Music (AI for recommendations) - https://www.amazon.com/primevideo - Recommendation AI (AI for personalized movie, TV show, and music recommendations)
Amazon Q Business - https://aws.amazon.com/q/business/ - Generative AI (Business-focused generative AI assistant for content creation, summarization, and task completion)
Amazon Q Developer - https://aws.amazon.com/q/developer/ - Generative AI (Generative AI coding assistant for developers)
Amazon Rekognition - https://aws.amazon.com/rekognition/ - Computer Vision (Image and video analysis, object detection, facial recognition)
Amazon Robotics - https://www.amazonrobotics.com/ - Robotics/Warehouse AI (AI for optimizing warehouse operations)
Amazon SageMaker - https://aws.amazon.com/sagemaker/ - Machine Learning Platforms & MLOps (Fully integrated development environment for end-to-end ML workflows)
Amazon Supply Chain - https://aws.amazon.com/aws-supply-chain/ - Supply Chain AI (AI for end-to-end supply chain visibility and insights)
Amper Music - https://www.ampermusic.com/ - Generative AI (AI Music Composition Platform)
AMP Robotics - https://www.amprobotics.com/ - Waste Management AI (AI-powered robotics for material recovery facilities)
Amplitude (AI features) - https://amplitude.com/solutions/ai-for-product - Product Analytics AI (AI for product analytics and growth insights)
Amplify (Manufacturing Execution System with AI) - https://www.amplify.ai/ - Manufacturing AI (AI for optimizing factory operations, scheduling, and performance)
Anomalo - https://www.anomalo.com/ - Data Quality AI (AI for automated data quality monitoring and anomaly detection)
Anyword - https://anyword.com/ - Generative AI (AI for crafting content optimized for conversions using data analysis)
Apple Health (AI for health insights) - https://www.apple.com/ios/health/ - Health AI (AI for analyzing health data from Apple Watch and other devices)
Apple Keyboard (Predictive Text, Autocorrect) - (Integrated into iOS/macOS) - NLP/Productivity AI (AI for predictive text suggestions, autocorrection, and grammar checking)
Apple Maps (AI for navigation, Look Around) - https://www.apple.com/ios/maps/ - Geospatial/Navigation AI (AI for routing, traffic prediction, and immersive street-level views)
Apple Music (AI for recommendations) - https://www.apple.com/apple-music/ - Recommendation AI (AI for personalized music recommendations and curated playlists)
Apple Photos (AI for recognition, search) - https://www.apple.com/ios/photos/ - Image/Media AI (AI for facial recognition, object detection, scene analysis, and intelligent search)
Arcwise AI - https://www.arcwise.ai/ - Business AI (Excel-based AI Data Analysis)
ARCHITEChTURES - https://architechtures.com/ - Architectural AI (AI for Generative Architectural Design)
ArchitectGPT - https://www.architectgpt.ai/ - Architectural AI (AI-Powered Property Design)
Arctic Wolf Aurora - https://arcticwolf.com/solutions/platform/ - Cybersecurity AI (AI-driven threat detection for endpoint security)
Arize AI - https://www.arize.com/ - MLOps (AI Observability & Model Monitoring)
Artbreeder - https://www.artbreeder.com/ - Generative Art AI (AI for generating and manipulating images across various categories)
Asana (AI features) - https://asana.com/ - Productivity AI (Project management with AI for task automation, dependency suggestions)
Ascent - https://www.ascent.ai/ - Financial AI (AI for regulatory compliance)
AssemblyAI - https://www.assemblyai.com/ - Conversational AI (Advanced Speech-to-Text API)
Atomic AI - https://atomic.ai/ - Biotech AI (AI for RNA-Targeting Drug Discovery)
Attestiv - https://attestiv.com/ - Digital Forensics AI (AI for digital media authentication and deepfake detection)
Audio.com (by Epidemic Sound) - https://www.audio.com/ - Music AI (AI for music search, recommendations, and stem separation)
AudioStack.ai - https://audiostack.ai/ - Generative AI (AI for Audio Production & Advertising)
Augury - https://www.augury.com/ - Industrial AI (AI for machine health and performance, focusing on specific industrial assets)
Aura Intelligent Systems - https://auraintelligent.com/ - Manufacturing AI (AI for Industrial Process Optimization)
Autodesk Forma - https://www.autodesk.com/products/forma/overview - Architectural AI (AI for Urban Planning & Environmental Analysis)
Avandra - https://www.avandra.com/ - Healthcare AI (AI-powered MRI interpretation and neuroimaging)
Baseten - https://www.baseten.co/ - Machine Learning Platforms & MLOps (AI app deployment software)
Be My Eyes (Be My AI) - https://www.bemyeyes.com/bemyai - Accessibility AI (AI Assistant for Visually Impaired)
BenevolentAI - https://www.benevolent.com/ - Drug Discovery AI (AI for Accelerating Drug Discovery)
BenchSci - https://www.benchsci.com/ - Life Sciences AI (AI for antibody and reagent selection in research)
BigID - https://bigid.com/ - Data Privacy AI (AI for discovering, classifying, and protecting sensitive data for privacy compliance)
BlackBox AI - https://www.blackbox.ai/ - Generative AI (AI code generation and completion)
Blackshark.ai - https://blackshark.ai/ - Geospatial AI (AI for 3D digital twin creation from satellite imagery)
Blockade Labs (Skybox AI) - https://www.blockadelabs.com/ - 3D Generative AI (AI for generating 360-degree interactive skyboxes/environments from text)
Blue Prism - https://www.blueprism.com/ - AI-Powered Automation (Robotic Process Automation (RPA))
BrainBox AI (ARIA) - https://brainboxai.com/ - Environmental AI (HVAC Optimization for Energy Efficiency)
Bright Machines - https://www.brightmachines.com/ - Factory Automation AI (AI-powered industrial automation for assembly and quality inspection)
BuildFire AI - https://buildfire.com/ai/ - Development AI (No-Code Mobile App Development)
Camira AI - https://camira.ai/ - Creative AI (Content Creation for Creatives)
Canva (Magic Studio AI) - https://www.canva.com/magic-studio/ - Design AI (AI suite for text-to-image, text-to-video, magic erase, etc.)
Carbon Chain - https://carbonchain.com/ - Supply Chain AI (AI for automated supply chain carbon emissions tracking and reporting)
Carbon Robotics - https://carbonrobotics.com/ - Agriculture AI (AI-Powered Laser Weeder)
CarbonBright - https://www.carbonbright.ai/ - Environmental AI (Product Carbon Footprint Assessment)
Carnegie Learning (Mika) - https://www.carnegielearning.com/who-we-are/ai-in-education/ - EdTech AI (AI-powered tutor for mathematics)
Casetext (CoCounsel) - https://casetext.com/ - Legal AI (Generative AI legal assistant for research, drafting, and analysis)
CausaLens - https://causalens.com/ - Explainable AI (XAI) (AI platform for causal AI)
Century Tech - https://www.century.tech/ - EdTech AI (AI-powered personalized learning platform for schools)
Character.ai - [suspicious link removed] - Large Language Models (LLMs) & Conversational AI (AI for role-play and interactive conversations)
Charisma.ai - https://charisma.ai/ - Game/Narrative AI (AI for creating interactive narratives and AI-driven characters)
Checkstep - https://www.checkstep.com/ - Content Moderation AI (AI for Automated Content Moderation)
ChowNow (OrderBetter AI) - https://orderbetter.ai/ - Food Service AI (AI for optimizing online ordering and delivery for restaurants)
Cisco Webex AI Agent - https://www.webex.com/products/calling/features/ai-voice-agent.html - Conversational AI (Self-service options and automated customer support)
Citrine Informatics - https://citrine.io/ - Materials Science AI (AI for Materials Discovery & Optimization)
Civitas (AI for Government) - https://www.civitas.ai/ - Public Sector AI (AI for government data analysis and civic engagement)
Clarifai - https://www.clarifai.com/ - Computer Vision (AI for image and video recognition, custom model training)
Clari - https://www.clari.com/ - Sales AI (AI for revenue operations)
Clay - https://www.clay.com/ - AI-Powered Business Applications (AI go-to-market tools)
Climate Engine - https://climateengine.org/ - Environmental AI (Cloud-based platform for environmental data & analytics)
Clipdrop (Stability AI) - https://clipdrop.co/ - Generative Art AI (AI-powered tools for image editing, upscaling, and composition)
Cloudera - https://www.cloudera.com/ - Machine Learning Platforms (Hybrid cloud data platform investing in AI assistants and RAG studio)
Coactive AI - https://coactive.ai/ - Data AI (Data labeling software)
Codeium - https://codeium.com/ - Generative AI (AI Code Completion & Generation)
Cognex (VisionPro Deep Learning) - https://www.cognex.com/products/deep-learning - Industrial AI (AI for complex defect detection and optical character recognition in manufacturing)
Cognito Forms (AI Features) - https://www.cognitoforms.com/ai - Productivity AI (AI for Form Creation & Data Extraction)
Cohere - https://cohere.com/ - Large Language Models (LLMs) & Conversational AI (Robust API for text generation, classification, summarization)
Collibra (AI Governance) - https://www.collibra.com/solutions/ai-governance - Data Governance AI (AI for data governance, quality, and metadata management)
Comet ML - https://www.comet.com/site/ - MLOps (ML Experiment Tracking & Model Monitoring)
Compliance.ai - https://www.compliance.ai/ - Regulatory Compliance AI (AI for regulatory change management)
Concentric AI - https://www.concentric.ai/ - Data Security AI (AI for Sensitive Data Discovery & Protection in Healthcare)
Consensus Cloud Solutions - https://www.consensus.com/ - Healthcare IT (Secure Messaging & AI)
Constructor.io - https://constructor.io/ - E-commerce Search AI (AI for product search and discovery optimization)
Contentsquare (AI features) - https://contentsquare.com/ - Customer Experience AI (AI for digital experience analytics and insights)
Copy.ai - https://www.copy.ai/ - Generative AI (AI-powered writing assistant for marketing, sales, and content creation)
Coqui - https://coqui.ai/ - Generative AI (Open-Source AI Voice Synthesis - Commercial Services)
Core ML (Apple) - https://developer.apple.com/documentation/coreml/ - On-device ML (Framework for integrating machine learning models directly into Apple apps)
Cortechs.ai (NeuroQuant) - https://www.cortechs.ai/ - Neuroimaging AI (AI for quantitative brain MRI analysis for neurodegenerative diseases)
Covariant.ai - https://covariant.ai/ - Robotics AI (AI for robotic manipulation in warehouses)
Credo AI - https://credo.ai/ - AI Governance (Policy-Driven AI Governance & Compliance)
CrowdStrike - https://www.crowdstrike.com/ - Cybersecurity AI (AI-driven endpoint protection)
Crystal (AI for Sales) - https://www.crystalknows.com/ - Sales AI (AI for analyzing prospect personalities to customize communication strategies)
Cursor - https://www.cursor.sh/ - Generative AI (AI-powered code editor for writing, editing, refactoring code with AI assistance)

Okay next chunk

Okay, here's the next chunk of the Unified AI Services List (D-E):

DALL-E 3 (OpenAI) - https://openai.com/dall-e-3 - Generative AI (Image generation from text descriptions)
Darktrace HEAL - https://darktrace.com/products/darktrace-heal - Cybersecurity AI (AI-powered cyber threat response)
Datafold - https://datafold.com/ - Data Observability AI (AI for data testing, lineage, and observability in data pipelines)
Dataiku - https://www.dataiku.com/ - Machine Learning Platforms & MLOps (Visual and code-based interface for data science and AI solutions)
Dataminr - https://www.dataminr.com/ - Operations AI (AI platform for real-time event, risk, and threat discovery in public data)
DataRobot - https://www.datarobot.com/ - Machine Learning Platforms & MLOps (Automates end-to-end process of building, deploying, and maintaining ML models)
Datature - https://datature.io/ - Computer Vision (No-code computer vision platform)
Databricks - https://www.databricks.com/ - Machine Learning Platforms & MLOps (Unified analytics platform for data engineering, ML, and analytics)
Daydream - https://daydream.shop/ - Retail AI (AI Chat-to-Shop for personalized fashion discovery)
Decagon - https://www.decagon.ai/ - AI-Powered Business Applications (AI agents for customer service)
Deep Instinct - https://www.deepinstinct.com/ - Cybersecurity AI (Applies deep learning to cybersecurity for threat prevention)
Deep 6 AI - https://www.deep6.ai/ - Healthcare AI (Clinical data management, analyzing EHRs)
DeepL - https://www.deepl.com/ - Large Language Models (LLMs) & Conversational AI (Highly accurate and naturally fluent language translation)
DeepMotion - https://www.deepmotion.com/ - Animation AI (AI for 3D animation from video or text)
DeepSeek - https://www.deepseek.com/ - Large Language Models (LLMs) & Conversational AI (Cost-efficient, open-source LLMs)
Deliveroo (AI-driven logistics) - https://corporate.deliveroo.co.uk/technology/ - Food Delivery AI (AI for rider allocation and delivery route optimization)
Descript - https://www.descript.com/ - Media AI (AI for Audio/Video Editing, Transcription, Overdub)
Diligent (AI insights) - https://www.diligent.com/solutions/ai-insights/ - Governance AI (AI for board governance, risk, and compliance insights)
DISCO (Cecilia AI) - https://www.csdisco.com/products/cecilia-ai/ - Legal AI (Generative AI for legal document analysis, summarization, and query)
DocJuris - https://docjuris.com/ - Legal AI (Contract review and negotiation platform with AI for deviation identification)
Drata - https://drata.com/ - Security & Compliance AI (AI for automated compliance & risk management)
DreamBox Learning - https://www.dreambox.com/ - EdTech AI (AI-driven personalized math and reading instruction)
DWE.ai (DeepWater Exploration) - https://dwe.ai/ - Marine AI (AI-powered computer vision for subsea operations, 3D reconstruction)
Eightfold AI - https://eightfold.ai/ - HR AI (AI for Talent Intelligence Platform)
EliseAI - https://eliseai.com/ - Real Estate AI (AI for real estate and property management)
ElevenLabs - https://elevenlabs.io/ - Generative AI (Ultra-realistic voice cloning and voice generation)
Enthought (Horizon) - https://www.enthought.com/platform/horizon - Scientific AI (AI platform for scientific data analysis and engineering R&D)
Envirosuite - https://envirosuite.com/ - Environmental AI (Real-time Environmental Monitoring & Management)
Evisort - https://www.evisort.com/ - Legal AI (AI for automating contract lifecycle management with intelligent search)
Exabyte.io - https://www.exabyte.io/ - Materials Science AI (Cloud platform for materials modeling and simulation with AI for property prediction)
Exabeam - https://www.exabeam.com/ - Cybersecurity AI (Security information and event management (SIEM) with AI for threat detection)
Exodigo - https://www.exodigo.com/ - Construction AI (AI for Underground Mapping & Site Intelligence)
Exscientia - https://www.exscientia.ai/ - Drug Discovery AI (AI-Driven Drug Design & Development)
Everlaw (AI Assistant) - https://www.everlaw.com/platform/everlaw-ai-assistant/ - Legal AI (AI for eDiscovery review, critical information surfacing, and argument crafting)
Everledger - https://www.everledger.io/ - Supply Chain AI (AI for Supply Chain Traceability & Sustainability)
Face ID (Apple) - https://support.apple.com/en-us/102551 - Biometric AI (AI for secure facial recognition)
FarmWise - https://farmwise.io/ - Agriculture AI (AI-powered weeding and farming robotics)
Fathom AI - https://fathom.fm/ - AI for Meetings (AI Notetaker & Summarizer)
Facebook Feed Ranking (AI-powered) - https://www.facebook.com/help/110994966629156 - Social Media AI (AI for personalizing content in news feeds)
Feedzai - https://feedzai.com/ - Financial AI (AI for real-time fraud prevention and risk management in financial services)
Fero Labs - https://www.ferolabs.com/ - Industrial AI (AI for predictive quality and process optimization in complex manufacturing)
Fiddler AI - https://www.fiddler.ai/ - AI Governance (Model Explainability, Bias Detection, Performance Monitoring)
Final Round AI - https://www.finalround.ai/ - Career AI (AI for Interview Preparation & Career Assistance)
Finch 3D - https://finch3d.com/ - Architectural AI (AI for Building Design Optimization)
Fireflies.ai - https://fireflies.ai/ - Meeting AI (AI for transcribing, summarizing, and analyzing voice conversations from meetings)
Fireworks AI - https://www.fireworks.ai/ - Machine Learning Platforms & MLOps (AI app development software)
Flatfile - https://flatfile.com/ - Data Management AI (AI-Assisted Data Onboarding)
Fliki.ai - https://fliki.ai/ - Video Creation AI (AI for turning text/blogs into videos with lifelike voices)
FlyPix AI - https://flypix.ai/ - Environmental AI (Geospatial Analysis for Environmental Monitoring)
Forethought - https://forethought.ai/ - Customer Service AI (AI for Customer Service Automation & Insights)
Formant - https://formant.io/ - Robotics AI (Robotics Management Platform)
Formlabs (Automation API with AI) - https://formlabs.com/automation-ecosystem/api/ - Industrial AI (AI for optimizing 3D printing workflows and material usage)
Forter - https://www.forter.com/ - E-commerce Fraud AI (AI for fraud prevention in online transactions)
FourKites - https://www.fourkites.com/ - Logistics AI (AI for real-time supply chain visibility and predictive ETAs)
Freshworks (Freddy AI) - https://www.freshworks.com/freshsales-crm/freddy-ai/ - CRM/Customer Service AI (AI assistant for sales productivity, customer support automation)
Futurepedia - https://www.futurepedia.io/ - AI Tool Directory (Comprehensive directory for AI tools)
GE Digital (GridOS) - https://www.ge.com/digital/products/grid-software - Energy AI (AI for grid orchestration, optimization, and DER management)
Genies - https://genies.com/ - Generative AI (AI for Digital Avatar Creation & Metaverse)
Gencove - https://www.gencove.com/ - Genomics AI (AI for low-pass genome sequencing and analysis)
Gero.ai - https://gero.ai/ - Longevity AI (AI for Anti-Aging Drug Discovery & Longevity Research)
Getfloorplan - https://getfloorplan.com/ - Design AI (AI for 2D/3D Floor Plans & Virtual Tours)
Gingko Bioworks (Cell Engineering Platform with AI) - https://www.gingkobioworks.com/ - Biotech AI (AI for designing and engineering organisms for various applications)
GitHub Copilot - https://github.com/features/copilot - Generative AI (AI-powered coding assistant)
Glean - https://www.glean.com/ - Enterprise AI (Work AI platform for enterprise search, knowledge connection, content generation)
Gloat - https://gloat.com/ - HR AI (AI for Talent Marketplace & Career Development)
Gong.io - https://www.gong.io/ - Sales AI (Conversation Intelligence for Sales)
Google AdSense (AI optimization) - https://adsense.google.com/start/ - Advertising AI (AI for optimizing ad placement, targeting, and revenue)
Google AI Studio - https://aistudio.google.com/ - Machine Learning Platforms (AI model experimentation)
Google Arts & Culture (AI features) - https://artsandculture.google.com/ - Cultural AI (AI for art recognition, style transfer, and personalized recommendations)
Google Assistant / Gemini in Android (On-device AI) - https://assistant.google.com/, https://developer.android.com/ai - Conversational AI/On-device AI (AI for voice commands, smart home control, app predictions)
Google Chrome (AI features) - https://www.google.com/chrome/ - Productivity AI (AI for tab organization, text summarization, smart autofill, phishing detection)
Google Cloud Contact Center AI Platform - https://cloud.google.com/contact-center-ai - Conversational AI (AI for building intelligent contact center solutions)
Google Cloud Document AI - https://cloud.google.com/document-ai - Document AI (AI for intelligent document processing, extracting data from various document types)
Google Cloud Natural Language AI - https://cloud.google.com/natural-language - Large Language Models (LLMs) & Conversational AI (Advanced text processing)
Google Cloud Vertex AI - https://cloud.google.com/vertex-ai - Machine Learning Platforms & MLOps (Unified environment for automated and custom ML model development)
Google Gemini - https://gemini.google.com/ - Large Language Models (LLMs) & Conversational AI (Multimodal AI for natural conversations, information, creative text)
Google Lens - https://lens.google/ - Image AI (AI for visual search, object identification, text extraction from images, and translation)
Google Maps (AI for Traffic, ETA, Live View) - https://maps.google.com/ - Geospatial/Navigation AI (AI for real-time traffic prediction, optimized routing, AR navigation)
Google Photos (AI features) - https://photos.google.com/ - Image/Media AI (AI for facial recognition, object recognition, smart album creation, automatic photo enhancements)
Google Play Store (AI for recommendations) - https://play.google.com/store - Recommendation AI (AI for personalized app and content recommendations)
Google Search (RankBrain, MUM, BERT, Gemini integration) - https://www.google.com/search - Search AI (AI for understanding search queries, ranking results, providing direct answers)
Google Translate (AI for real-time translation) - https://translate.google.com/ - NLP/Translation AI (AI for real-time voice and image translation)
Google Workspace (AI in Docs, Sheets, Slides, Gmail) - https://workspace.google.com/ - Productivity AI (AI for smart compose, smart reply, grammar correction, data analysis)
Grain.com - https://grain.com/ - Meeting AI (AI for recording, transcribing, and sharing key moments from video meetings)
Grammarly - https://www.grammarly.com/ - Generative AI (AI writing partner for grammar, spelling, style, and tone)
GrayMatter Robotics - https://www.graymatter-robotics.com/ - Industrial AI (AI for industrial robots)
Greenlight Guru - https://www.greenlight.guru/ - Healthcare AI (AI for medical device quality management)
Greyparrot - https://greyparrot.ai/ - Waste Management AI (AI-powered waste analysis platform)
Grubhub (AI features) - https://www.grubhub.com/ - Food Delivery AI (AI for personalized recommendations and delivery optimization)
H2O.ai - https://h2o.ai/ - Machine Learning Platforms & MLOps (Open-source AI platforms and data science platforms)
Harvey AI - https://www.harvey.ai/ - Legal AI (Generative AI for Legal Professionals)
HashiCorp - https://www.hashicorp.com/ - Infrastructure AI (Automates and secures hybrid cloud infrastructure for GenAI)
Hawk AI - https://hawk.ai/ - Financial AI (AI for Anti-Money Laundering & Fraud Detection)
Hebbia - https://hebbia.com/ - AI-Powered Business Applications (General purpose AI for finance and legal)
Heliogen - https://heliogen.com/ - Clean Energy AI (AI for optimizing concentrated solar power systems and energy generation)
Heuritech - https://heuritech.com/ - Fashion AI (AI for fashion trend forecasting)
Highspot - https://www.highspot.com/ - Sales Enablement AI (AI for Sales Content & Guidance)
Hippocratic AI - https://www.hippocratic.ai/ - Healthcare AI (Generative AI for Healthcare)
Hook (AI Music) - https://hook.ai/ - Generative AI (AI-powered music remixing)
HubSpot (Breeze AI) - https://www.hubspot.com/ai - Marketing/CRM AI (AI suite built into HubSpot CRM for content generation, task automation, and data insights)
Hugging Face (Platform/API) - https://huggingface.co/ - Large Language Models (LLMs) & Conversational AI (Access to pre-trained NLP models, platform/API)
Hypar - https://hypar.io/ - Architectural AI (Generative Design for Buildings)
Hyperscience - https://www.hyperscience.com/ - Business AI (Intelligent Document Processing)
IBM Environmental Intelligence Suite - https://www.ibm.com/products/environmental-intelligence-suite - Environmental AI (AI for climate risk assessment, environmental monitoring, and sustainability insights)
IBM Garage (AI solutions) - https://www.ibm.com/garage - AI Consulting/Solutions (Methodology and service for rapid development and deployment of AI solutions)
IBM Maximo Application Suite (AI features) - https://www.ibm.com/products/maximo - Industrial AI (AI for asset performance management, predictive maintenance)
IBM Security QRadar Suite (AI features) - https://www.ibm.com/products/qradar-suite - Cybersecurity AI (AI for SIEM and SOAR)
IBM Sterling Supply Chain Intelligence Suite (AI features) - https://www.ibm.com/products/sterling-supply-chain-intelligence-suite - Supply Chain AI (AI for supply chain visibility, risk detection, and optimization)
IBM Turbonomic (AI for AIOps) - https://www.ibm.com/cloud/turbonomic - AIOps (AI for application resource management and network performance optimization)
IBM Watson NLP - https://www.ibm.com/cloud/watson-natural-language-processing - Large Language Models (LLMs) & Conversational AI (Text analysis, emotion detection, relationship extraction)
IBM Watson OpenScale - https://www.ibm.com/cloud/watson-openscale - AI Governance (AI Governance, Fairness Checks, Explainability)
IBM Z and Cloud Modernization Stack (AI capabilities) - https://www.ibm.com/products/z-and-cloud-modernization-stack - Enterprise AI (AI for modernizing mainframe applications and integrating them with cloud AI services)
ICEYE - https://www.iceye.com/ - Geospatial AI (AI for Synthetic Aperture Radar (SAR) satellite imagery analysis)
Image Creator in Bing (Microsoft) - https://www.bing.com/create - Generative Art AI (AI for generating images from text descriptions)
Infogrid - https://infogrid.io/ - Environmental AI (Smart Building Management & Energy Efficiency)
Insilico Medicine - https://www.insilico.com/ - Drug Discovery AI (AI for Drug Discovery & Development)
Insitro - https://www.insitro.com/ - Drug Discovery AI (Machine learning for drug discovery and development)
Instrument Systems (Luminance Pro AI) - https://www.instrumentsystems.com/en/products/light-measurement/luminance-and-color-measurement-cameras/luminance-pro-ai/ - Industrial AI (AI for optical quality control in displays and light sources)
InstaDeep (acquired by BioNTech) - https://www.instadeep.com/ - Biotech AI (AI for Drug Discovery & Reinforcement Learning in Biotech)
Interior AI - https://interiorai.com/ - Design AI (AI for Interior Design Concepts)
Intercom - https://www.intercom.com/ - AI-Powered Business Applications (AI-first customer service platform)
IQVIA Healthcare-grade AI - https://www.iqvia.com/solutions/innovative-models/artificial-intelligence-and-machine-learning - Healthcare AI (AI solutions for life sciences and healthcare)
Iterative.ai (DVC, CML) - https://iterative.ai/ - MLOps (Open-source MLOps Tools for Data/Model Versioning)
Jasper - https://www.jasper.ai/ - Generative AI (AI assistant for generating on-brand online content)
Jukebox (OpenAI) - https://openai.com/research/jukebox - Music AI (Generative AI that creates music, including singing, in various styles)
Kaedim - https://www.kaedim3d.com/ - 3D Generative AI (AI for generating 3D models from 2D images)
Katalist AI - https://www.katalist.ai/ - Generative AI (YouTube Video Automation)
Kayrros - https://www.kayrros.com/ - Environmental AI (AI for global energy and environmental intelligence, including methane emissions tracking)
Kebotix - https://www.kebotix.com/ - Materials Science AI (AI for Autonomous Materials Discovery)
Kensho Technologies - https://kensho.com/ - Financial AI (AI for financial intelligence)
Kira Systems (Litera) - https://www.litera.com/ - Legal AI (AI for extracting and analyzing contract provisions for due diligence)
Knewton Alta - https://www.knewton.com/products/alta/ - EdTech AI (Adaptive learning platform using AI for personalized instruction)
KNIME Analytics Platform - https://www.knime.com/ - Machine Learning Platforms & MLOps (End-to-end data science platform)
Kore.ai - https://kore.ai/ - Conversational AI (Enterprise conversational AI platform for virtual assistants and process automation)
Kustomer - https://www.kustomer.com/ - AI-Powered Business Applications (AI-powered customer service platform)
LabGenius - https://www.labgenius.com/ - Biotech AI (AI-driven discovery platform for novel therapeutic proteins)
Labelbox - https://labelbox.com/ - Data AI (Training Data Platform for ML)
LANDR (AI Mastering) - https://www.landr.com/ - Music AI (AI for audio mastering)
Landing.ai (LandingLens) - https://landing.ai/landinglens/ - Industrial AI (Computer Vision platform for visual inspection in manufacturing)
LangChain - https://www.langchain.com/ - Machine Learning Platforms & MLOps (AI app development tools for building LLM-powered applications)
Lawyer.com AI - https://www.lawyer.com/ai/ - Legal AI (AI for Legal Research & Assistance)
Lectra (Valia Fashion, AI features) - https://www.lectra.com/en/solutions/valia-fashion - Fashion AI (AI for pattern making, material estimation, and production optimization)
LegalZoom (AI features) - https://www.legalzoom.com/ - Legal AI (AI for guiding users through legal document creation and business formation)
Legly - https://legly.com/ - Legal AI (AI for contract analysis for small to mid-sized firms)
Lexion - https://www.lexion.ai/ - Legal AI (AI for contract management and legal agreement analysis)
Lily AI - https://www.lily.ai/ - Retail AI (AI for product descriptions in retail)
Luma AI (Genie) - https://lumalabs.ai/genie - 3D Generative AI (AI for generating 3D models and environments from text or images)
Lumen5 - https://lumen5.com/ - Generative AI (AI for turning text/blogs into short videos)
Luminance - https://www.luminance.com/ - Legal AI (Enterprise contract automation)
Machina Labs - https://machinalabs.com/ - Manufacturing AI (AI for manufacturing)
Mailmodo (AI Email Template Generator) - https://www.mailmodo.com/ - Marketing AI (AI for email marketing templates)
Maket.ai - https://maket.ai/ - Architectural AI (AI for Floor Plan & Layout Generation)
Materials Zone - https://www.materials.zone/ - Materials Science AI (AI for materials data management and analysis)
Memex - (No direct service URL, research tool) - AI-Powered Business Applications (AI research tool for gathering, organizing, synthesizing information)
Mercor - https://www.mercor.ai/ - AI-Powered Business Applications (AI-powered hiring platform)
Meta AI (across apps) - https://about.fb.com/news/2024/04/introducing-meta-ai-our-new-assistant/ - Conversational AI/Generative AI (Meta's AI assistant integrated into WhatsApp, Messenger, Instagram, and Facebook)
Meta Reality Labs (AI for VR/AR) - https://www.metarealitylabs.com/ - VR/AR AI (AI for hand tracking, eye tracking, spatial audio, and realistic avatar animation in VR/AR experiences)
Metropolis Technologies - https://metropolis.io/ - Smart City AI (AI for parking management)
Microsoft 365 Copilot - https://www.microsoft.com/en-us/microsoft-365/microsoft-copilot - AI-Powered Business Applications (AI assistant integrated into Microsoft 365 for productivity)
Microsoft Azure AI Language (Text Analytics) - https://azure.microsoft.com/en-us/products/ai-services/ai-language - Large Language Models (LLMs) & Conversational AI (Sentiment analysis, language detection, key phrase extraction)
Microsoft Azure Machine Learning - https://azure.microsoft.com/en-us/products/machine-learning - Machine Learning Platforms & MLOps (Comprehensive MLaaS platform for developing, deploying, and managing ML models)
Microsoft Azure Percept (Edge AI) - https://azure.microsoft.com/en-us/products/azure-percept - Edge AI (Platform for accelerating AI at the edge with pre-built models for vision and speech)
Microsoft Copilot Studio - https://www.microsoft.com/en-us/microsoft-copilot/microsoft-copilot-studio - Conversational AI (Low-code platform for customizing Copilot and building custom AI assistants)
Microsoft Defender for Cloud Apps (AI-powered) - https://learn.microsoft.com/en-us/defender-cloud-apps/what-is-defender-for-cloud-apps - Cybersecurity AI (AI for cloud security broker, threat detection, and compliance monitoring)
Microsoft Designer - https://designer.microsoft.com/ - Generative Art AI (AI for creating custom images from text descriptions, photo editing, background removal)
Microsoft Dynamics 365 Copilot (Specific Modules) - https://www.microsoft.com/en-us/dynamics-365/solutions/ai - Enterprise AI (AI for various Dynamics 365 modules like Sales, Service, Finance, Supply Chain)
Microsoft Entra Verified ID (AI features) - https://www.microsoft.com/en-us/security/business/identity-access/microsoft-entra-verified-id - Identity AI (AI for secure, decentralized identity verification)
Microsoft FarmBeats for Azure Data Manager for Agriculture - https://azure.microsoft.com/en-us/solutions/agriculture/ - Agriculture AI (AI for data integration, analytics, and insights for precision agriculture)
Microsoft Immersive Reader (AI features) - https://support.microsoft.com/en-us/topic/microsoft-immersive-reader-f967a5b3-2415-4673-bc97-f70355f30328 - EdTech AI/Accessibility AI (AI for enhanced reading, comprehension, and language translation)
Microsoft Lens (AI features) - https://www.microsoft.com/en-us/microsoft-365/microsoft-lens - Productivity AI (AI for scanning documents, whiteboards, business cards)
Microsoft Photo Editor (AI features) - (Integrated into Windows Photos app) - Image AI (AI for automatic image enhancement, background blur, object removal)
Microsoft Project Cortex (SharePoint Syntex) - (now integrated into Microsoft 365 services as part of Microsoft Viva Topics) - Knowledge Management AI (AI for content understanding, classification, and knowledge discovery)
Microsoft Security Copilot - https://www.microsoft.com/en-us/security/business/ai-security/microsoft-security-copilot - Cybersecurity AI (AI for cybersecurity threat identification, automated responses)
Microsoft Teams AI Features (Granular) - https://nboldapp.com/top-10-ai-features-in-microsoft-teams-for-better-teamwork/ - Communication AI (AI for meeting transcripts, auto-notes, live translation, smart task assignment)
Microsoft To Do (AI suggestions) - https://todo.microsoft.com/ - Productivity AI (AI for intelligent suggestions for tasks based on emails and calendar events)
Midjourney - https://www.midjourney.com/ - Generative AI (Artistic and dreamlike image generation)
Mintlify - https://mintlify.com/ - Generative AI (AI for simplifying documentation creation)
Mistral AI (La Plateforme) - https://mistral.ai/news/la-plateforme/ - Large Language Models (LLMs) & Conversational AI (Access to Mistral's open-source LLMs)
Mixpanel (AI features) - https://mixpanel.com/solutions/ai-for-product-analytics/ - Product Analytics AI (AI for user behavior analysis and product decision making)
Moixa - https://www.moixa.com/ - Energy Storage AI (AI for optimizing battery storage and smart charging)
Modl:test - https://www.modl.ai/ - Game Development AI (AI for Game Testing & QA)
Monday.com (AI features) - https://monday.com/ai/ - Project Management AI (AI for task automation, intelligent summaries, and workflow optimization)
Monte Carlo - https://www.montecarlodata.com/ - Data Observability AI (AI for data reliability, monitoring data quality, and anomaly detection)
Mostly AI - https://mostly.ai/synthetic-data-generation - Data AI (Synthetic Data Generation)
Motive (formerly KeepTruckin) - https://gomotive.com/ - Industrial AI (AI-powered fleet management and safety)
Move.ai - https://www.move.ai/ - Animation AI (AI for Motion Capture from Video)
Moveworks - https://www.moveworks.com/ - IT & HR AI (AI for Employee Support & Automation)
Narvar (AI-powered post-purchase) - https://corp.narvar.com/platform/ai/ - E-commerce AI (AI for post-purchase customer experience, tracking, returns)
Nanonets - https://nanonets.com/ - Business AI (AI-Powered Document Processing)
Netflix Recommendation Engine - https://help.netflix.com/en/node/100632 - Recommendation AI (AI for personalized movie and TV show recommendations)
Nexthink - https://www.nexthink.com/ - IT Operations AI (Digital Employee Experience Management)
NoTraffic - https://notraffic.tech/ - Urban Mobility AI (AI for optimizing traffic flow at intersections)
Notion AI - https://www.notion.so/product/ai - AI-Powered Business Applications (AI-powered assistance for note-taking, document drafting, collaborative workspaces)
Nuance Mix - https://www.nuance.com/omni-channel-customer-engagement/mix/ - Conversational AI (AI for building conversational AI assistants)
NVIDIA BioNeMo - https://developer.nvidia.com/bionemo - Drug Discovery AI (Generative AI framework for drug discovery)
NVIDIA Earth-2 - https://www.nvidia.com/en-us/climatetech/earth-2/ - Climate AI (AI for high-resolution climate modeling and simulation)
NVIDIA Metropolis - https://www.nvidia.com/en-us/industries/smart-cities/metropolis/ - Smart City/Vision AI (AI application framework for video analytics)
NVIDIA NeMo - https://developer.nvidia.com/nemo - Generative AI (Framework for building, customizing, and deploying generative AI models for speech and language)
NVIDIA Omniverse (AI-enabled features) - https://www.nvidia.com/en-us/omniverse/ - Digital Twin/Simulation AI (AI for building and operating industrial metaverse applications)
NVIDIA Riva - https://developer.nvidia.com/riva - Conversational AI (SDK for building AI speech and translation services)
NVIDIA TAO Toolkit - https://developer.nvidia.com/tao - MLOps/Vision AI (Low-code AI framework for building custom vision AI models)
Objaverse (Google DeepMind) - https://www.deepmind.com/open-source/objaverse - 3D Content AI (Large dataset of 3D objects for training generative AI)
Observe.ai - https://www.observe.ai/ - Customer Service AI (AI for Contact Center Automation & QA)
OCI Anomaly Detection (Oracle) - https://www.oracle.com/artificial-intelligence/ai-services/ - Cloud AI (AI for detecting anomalies in time-series data)
OCI Document Understanding (Oracle) - https://www.oracle.com/artificial-intelligence/ai-services/ - Cloud AI (AI for extracting data from documents)
OCI Forecasting (Oracle) - https://www.oracle.com/artificial-intelligence/ai-services/ - Cloud AI (AI for time-series forecasting)
OCI Language (Oracle) - https://www.oracle.com/artificial-intelligence/ai-services/ - Cloud AI (AI for text analysis)
OCI Speech (Oracle) - https://www.oracle.com/artificial-intelligence/ai-services/ - Cloud AI (AI for converting speech to text)
OCI Vision (Oracle) - https://www.oracle.com/artificial-intelligence/ai-services/ - Cloud AI (AI for image recognition and analysis)
Oolo AI - https://oolo.ai/ - Customer Service AI (AI-Powered Customer Care Solutions)
Ontra - https://www.ontra.ai/ - Legal AI (AI for contract automation and insights for private markets)
OpenAI API - https://openai.com/docs/api-reference - Large Language Models (LLMs) & Conversational AI (Access to GPT models for text generation, understanding)
OpenGrid - https://opengrid.com/ - Public Sector AI (AI for civic data analysis and smart city initiatives)
OpenText EnCase Forensic - https://www.opentext.com/products/forensic - Digital Forensics AI (Digital Evidence & Forensics Software with AI capabilities)
Operator by OpenAI - (No direct service URL, often integrated via OpenAI API) - Conversational AI (Automates routine customer service tasks)
Oracle Digital Assistant - https://www.oracle.com/chatbots/digital-assistant/ - Conversational AI (Platform for building enterprise chatbots and virtual assistants)
Oracle Fusion Cloud Applications (AI features) - https://www.oracle.com/applications/ai-ml.html - Enterprise AI (AI for various Oracle Fusion Cloud Applications like ERP, HCM, SCM, CRM)
Oracle Cloud Infrastructure (OCI) AI Services - https://www.oracle.com/artificial-intelligence/ai-services/ - Cloud AI (Suite of AI services on OCI)
Orbital Insight - https://orbitalinsight.com/ - Geospatial AI (AI for geospatial intelligence and satellite imagery analysis)
Orli - https://orlifertility.com/ - Healthcare AI (AI in fertility tracking and reproductive health)
Originality.ai - https://originality.ai/ - Content AI (AI content and plagiarism detection)
Otter.ai - https://otter.ai/ - Conversational AI (Meeting Transcription & Summary)
Outfunnel - https://outfunnel.com/ - AI-Powered Automation (Sales and marketing data integration platform)
Pachyderm - https://www.pachyderm.com/ - MLOps (Data Versioning & Pipelines for ML)
Path Robotics - https://www.pathrobotics.com/ - Industrial Robotics AI (AI for autonomous welding robots)
Pendo (AI features) - https://www.pendo.io/platform/ai/ - Product Analytics AI (AI for product usage insights and user behavior analytics)
Persefoni - https://persefoni.com/ - Environmental AI (Carbon Accounting & Management Platform)
Perplexity AI - https://www.perplexity.ai/ - Large Language Models (LLMs) & Conversational AI (AI search engine)
Photoroom - https://www.photoroom.com/ - Image AI (Photo editing app)
Phytoform Labs - https://phytoformlabs.com/ - Agriculture Biotech AI (AI for Crop Trait Discovery & Gene Editing)
Picarro - https://www.picarro.com/ - Environmental AI (AI for high-precision gas analysis for greenhouse gas monitoring and leak detection)
PicWish - https://picwish.com/ - Image AI (AI for background removal, image enhancement, and object removal)
Pictory AI - https://pictory.ai/ - Generative AI (Turning long-form content into short videos)
Pika Labs - https://pika.art/ - Generative AI (Video generation service)
Pitch (AI-powered presentations) - https://pitch.com/ - Productivity AI (AI-powered presentations)
Planet Labs (Planet Analytics) - https://www.planet.com/products/planet-analytics/ - Geospatial AI (AI for satellite imagery analysis for environmental and agricultural insights)
Planetary AI - https://www.planetary.ai/ - Environmental AI (AI for Climate Risk & Resilience Planning)
Playform.ai - https://www.playform.ai/ - Creative AI (AI for Fine Art & Generative Design)
Playground AI - https://playground.ai/ - Generative Art AI (Online AI image creation tool)
Plus One Robotics (PickOne) - https://plusonerobotics.com/ - Warehouse Robotics AI (AI for vision-guided picking robots)
Polis - https://pol.is/ - Social AI (AI for identifying consensus and divisive topics in large-scale online conversations)
Polymateria - https://polymateria.com/ - Materials Science AI (AI for creating biodegradable plastics)
PrecisionHawk - https://precisionhawk.com/ - Agriculture AI (Drone Data Analytics for Agriculture)
PredictNow.ai - https://www.predictnow.ai/ - Financial AI (Hedge Fund Investment AI)
Project44 - https://www.project44.com/ - Logistics AI (AI for real-time transportation visibility and predictive ETAs)
Promethean AI - https://prometheanai.com/ - Game Development AI (AI for Game Environment Creation)
Prospera - https://www.prospera.ag/ - Agriculture AI (AI for Crop Health & Yield Optimization)
PTV Group (Optima) - https://www.ptvgroup.com/en/solutions/traffic-software/ptv-optima/ - Urban Mobility AI (AI for real-time traffic management and forecasting)
Pymetrics - https://www.pymetrics.com/ - HR AI (AI for fair and bias-free talent assessment)
Pypestream - https://www.pypestream.com/ - Conversational AI (AI for Customer Service Automation)
Quantexa - https://www.quantexa.com/ - AI-Powered Business Applications (AI-powered data analytics for financial institutions, fraud detection)
QuantumBlack (McKinsey & Company) - https://www.mckinsey.com/capabilities/quantumblack/overview - AI Consulting/Solutions (Applies advanced AI to complex business problems)
Querium - https://querium.com/ - EdTech AI (AI tutor for STEM subjects)
QuickBooks (AI features) - https://quickbooks.intuit.com/ - AI-Powered Business Applications (AI automates invoicing, expense tracking, financial reporting)
Qmunity (Quantum Machines) - https://quantum-machines.co/ - Quantum AI (Quantum Control for AI & Scientific Research)
Rasa - https://rasa.com/ - Large Language Models (LLMs) & Conversational AI (Open-source conversational AI framework for chatbots)
Read Easy.AI - https://readeasy.ai/ - Accessibility AI (AI for Text Simplification & Readability)
Realtime Robotics (RapidPlan) - https://rtr.ai/ - Robotics AI (Motion Planning AI for Industrial Robots)
Realtor.com (AI features) - https://www.realtor.com/ - Real Estate AI (AI for home recommendations and market insights)
Recycleye - https://www.recycleye.com/ - Waste Management AI (AI & Robotics for Waste Classification and Sorting)
Recursion Pharmaceuticals - https://www.recursionpharma.com/ - Drug Discovery AI (AI-Driven Drug Discovery Platform)
Reejig - https://reejig.com/ - HR AI (AI for Workforce Intelligence & Sustainability Skills)
Relativity (aiR) - https://www.relativity.com/products/relativityone/ai/ - Legal AI (AI suite for eDiscovery, case strategy, and privilege review)
Rephrase.ai - https://rephrase.ai/ - Generative Video AI (AI for Personalized Video Creation)
Replit (Ghostwriter) - https://replit.com/site/ghostwriter - Generative AI (AI for generating code from natural language prompts)
Replica Studios - https://www.replicastudios.com/ - Generative AI (AI Voice Actor Platform)
Retrain.ai - https://www.retrain.ai/ - Workforce AI (AI for workforce intelligence, skill identification, and talent mobility)
Reveal - https://www.revealdata.com/ - Legal AI (AI-powered eDiscovery platform for legal review and analysis)
RightHand Robotics - https://www.righthandrobotics.com/ - Robotics AI (AI for robotic piece-picking in logistics and e-commerce)
Riskified - https://www.riskified.com/ - E-commerce AI (AI for e-commerce fraud prevention)
Roofstock (AI for Investment) - https://www.roofstock.com/ - Real Estate AI (AI for single-family rental property investment analysis)
Runway - https://runwayml.com/ - Generative AI (AI-driven video editing and creation)
Saildrone - https://www.saildrone.com/ - Maritime AI (AI for uncrewed surface vehicles for ocean data collection)
Salesforce Einstein (Sales Cloud) - https://www.salesforce.com/solutions/ai/generative-ai/ - AI-Powered Business Applications (AI-powered CRM optimization, predictive analytics)
Salesforce Net Zero Cloud (AI features) - https://www.salesforce.com/products/net-zero-cloud/ - Sustainability AI (AI for tracking, managing, and reducing carbon emissions)
Samsara - https://www.samsara.com/ - Industrial AI (IoT platform with AI for operations and safety)
SAP AI Core - https://www.sap.com/products/technology-platform/ai-core.html - MLOps/Enterprise AI (Platform for building and deploying enterprise-grade AI models)
SAP Business AI - https://www.sap.com/products/technology-platform/ai.html - Enterprise AI (AI embedded across SAP's suite of business applications)
SatSure - https://satsure.co/ - Geospatial AI (AI for satellite-based analytics for agriculture, banking, and climate insights)
Scale AI - https://scale.com/ - Machine Learning Platforms & MLOps (Data labeling and AI infrastructure)
Schrodinger (AI-enabled platform) - https://www.schrodinger.com/ - Drug Discovery AI (AI-enabled computational platform for drug discovery)
Seeq - https://www.seeq.com/ - Industrial AI (Advanced Analytics for Process Manufacturing)
Seeing AI (Microsoft) - https://www.microsoft.com/en-us/ai/seeing-ai - Accessibility AI (AI for Visually Impaired, describes surroundings)
Sense (Home Energy AI) - https://sense.com/ - Home Energy AI (AI for home energy monitoring and insights)
Senseye (Siemens) - https://www.senseye.io/ - Industrial AI (AI for predictive maintenance, acquired by Siemens)
Seon - https://seon.io/ - Fraud Prevention AI (AI for online fraud prevention based on digital footprints)
ServiceNow (Now Platform AI) - https://www.servicenow.com/ai.html - IT/Workflow AI (AI for automating IT service management, customer service workflows)
Sewbo - (Website appears defunct, concept is AI-controlled robotic garment assembly) - Manufacturing AI (AI for automated garment sewing)
Shield AI - https://shield.ai/ - Defense AI (Autonomous Drones & AI for Defense)
Siemens Grid Software (AI capabilities) - https://www.siemens.com/global/en/products/energy/grid-software.html - Energy AI (AI for energy management, predictive maintenance, and grid stability)
Sierra - https://www.sierra.ai/ - AI-Powered Business Applications (Customer service software)
Six Atomic - https://www.sixatomic.com/ - Fashion AI (AI for streamlining design to manufacturing workflows in fashion)
SkyHive - https://skyhive.ai/ - HR AI (AI for skills-based workforce transformation)
Slack (Slack GPT) - https://slack.com/ai - Communication AI (AI for summarizing conversations, drafting messages, and answering questions)
SlidesAI - https://slidesai.io/ - Productivity AI (AI for Presentations)
Slang.ai - https://slang.ai/ - Conversational AI (Digital phone concierge)
Snorkel AI - https://snorkel.ai/ - Data AI (Programmatic Data Labeling)
Snyk (AI features) - https://snyk.io/ - Cybersecurity AI (AI for code security analysis and vulnerability detection)
Sophia Genetics - https://www.sophiagenetics.com/ - Genomics AI (AI for data-driven medicine, particularly genomics and radiomics)
Soundraw - https://soundraw.io/ - Generative AI (AI Music Generator)
Soundry AI - https://soundry.ai/ - Generative AI (Text-to-Sound & Infinite Sample Packs)
SPOTIO - https://spotio.com/ - Sales AI (AI for lead generation, task automation, route planning)
Spotify Recommendation Engine - https://spotify.com/ - Recommendation AI (AI for personalized music recommendations)
Spotify Podcast AI (Ad Insertion, Transcripts) - (Integrated into platform) - Audio AI (AI for dynamic ad insertion in podcasts, automated transcription)
SpotDraft - https://spotdraft.com/ - Legal AI (AI for end-to-end contract automation)
Stable Diffusion - https://stability.ai/stable-diffusion - Generative AI (Open-source image generation)
StackBlitz (AI features) - https://stackblitz.com/ - Development AI (Web and mobile app development with AI features)
StemRoller (Acon Digital) - https://acondigital.com/products/stemroller/ - Audio AI (AI for high-quality audio stem separation)
StormGeo (AI-powered Weather) - https://www.stormgeo.com/ - Maritime/Energy AI (AI for weather forecasting and route optimization for shipping and offshore)
Striveworks - https://www.striveworks.com/ - MLOps (MLOps for government and defense)
Suno - https://www.suno.ai/ - Generative AI (Music and sound generation)
Superb AI - https://www.superb-ai.com/ - Data AI (Data Labeling & Annotation Platform)
Symbio Robotics (SymbioDCS) - https://symbiorobotics.com/ - Robotics AI (AI for industrial robot programming and optimization)
Symbl.ai - https://symbl.ai/ - Conversational AI (Conversational intelligence (speech-to-text, sentiment, topics))
Synthesia - https://www.synthesia.io/ - Generative AI (AI-powered platform for realistic human avatars and video creation)
Tableau with AI - https://www.tableau.com/products/features/ai - Business Intelligence AI (AI capabilities for business intelligence, predictive insights)
Tabnine - https://www.tabnine.com/ - Generative AI (AI code assistant for intelligent code completion)
Tamr - https://www.tamr.com/ - Data Unification AI (AI for data mastering, cleaning, and unification from disparate sources)
Taranis - https://taranis.com/ - Agriculture AI (AI for Crop Monitoring & Disease Detection)
Tastewise - https://tastewise.io/ - Food Tech AI (AI for food trend analysis and new product development)
Tavus - https://www.tavus.io/ - Generative AI (Video Production & Personalization)
Tempus - https://www.tempus.com/ - Healthcare AI (Data-driven precision medicine for fighting disease)
Tesla Autopilot / FSD (AI) - https://www.tesla.com/autopilot - Autonomous Driving AI (AI for advanced driver-assistance systems)
Tesla Optimus (AI for Humanoid Robot) - https://www.tesla.com/AI - Robotics AI (AI for general-purpose humanoid robot)
TestFit - https://testfit.io/ - Architectural AI (AI for Feasibility Studies & Urban Planning)
Textio - https://textio.com/ - HR AI (AI for Inclusive Job Descriptions & Communications)
The Climate Corporation (FieldView) - https://climate.com/ - Agriculture/Environmental AI (AI for predictive insights on crop performance)
There's An AI For That - https://theresanaiforthat.com/ - AI Tool Directory (Directory for AI tools based on tasks)
ThoughtRiver - https://www.thoughtriver.com/ - Legal AI (AI for contract review and negotiation)
TikTok For You Page Algorithm - https://www.tiktok.com/for-you - Recommendation AI (AI for highly personalized short-form video recommendations)
TikTok Content Moderation (AI for harmful content) - (Internal systems) - Content Moderation AI (AI for identifying and removing harmful content)
Toast (AI-powered scheduling) - https://pos.toasttab.com/restaurant-management/schedules - Food Service AI (AI for restaurant staff scheduling optimization)
Tome - https://tome.app/ - Generative AI (AI for Presentations & Storytelling)
Topaz Labs (AI Image Suite) - https://www.topazlabs.com/ - Image AI (AI for image upscaling, noise reduction, and sharpening)
Tractian - https://tractian.com/ - Industrial AI (Predictive maintenance using AI and IoT for industrial machinery)
Trellix (AI-powered XDR) - https://www.trellix.com/en-us/solutions/extended-detection-response/xdrs.html - Cybersecurity AI (AI for extended detection and response across security layers)
Truepic - https://www.truepic.com/ - Authenticity AI (AI for image and video authentication, combating deepfakes)
Two Hat (AI content moderation) - https://www.twohat.com/ - Content Moderation AI (AI for online content moderation and community safety)
Typeface - https://www.typeface.ai/ - Generative AI (On-Brand Content for Enterprise)
Unspun (FitOS) - https://unspun.io/ - Retail AI (AI for personalized clothing sizing and custom production)
UrbanFootprint - https://urbanfootprint.com/ - Urban Planning AI (AI for Sustainable Urban Development & Resilience)
Urbint - https://www.urbint.com/ - Infrastructure AI (AI for predicting infrastructure risk and optimizing operations for utilities)
Valo Health - https://www.valohealth.com/ - Drug Discovery AI (AI-Powered Drug Discovery & Development)
Vanti Analytics - https://www.vantianalytics.com/ - Industrial AI (AI for predictive quality and root cause analysis in manufacturing)
Varda Space Industries - https://www.varda.com/ - Space AI (AI for In-space Manufacturing & Operations)
VAST Data - https://www.vastdata.com/ - Machine Learning Platforms & MLOps (AI data infrastructure software)
Veras - https://www.evolvelab.io/veras - Architectural AI (AI for Architectural Visualization & Rendering)
Verity (Exotec) - https://www.exotec.com/verity/ - Warehouse AI (AI-powered drones for warehouse inventory management)
Voiceitt - https://voiceitt.com/ - Accessibility AI (Speech Recognition for Non-Standard Speech)
Vortexa - https://www.vortexa.com/ - Supply Chain AI (AI for optimizing supply chains and logistics)
Waycare - https://waycaretech.com/ - Urban Mobility AI (AI for predictive traffic analytics and incident prevention)
Waymo (Autonomous Driving AI) - https://waymo.com/ - Autonomous Driving AI (AI for self-driving vehicles, perception, prediction, and planning)
WebWhiz AI - https://webwhiz.ai/ - Conversational AI (AI Chatbot for Websites)
Weights & Biases - https://wandb.ai/ - MLOps (Experiment Tracking & Model Management)
Whalesync - https://whalesync.com/ - AI-Powered Automation (Bidirectional data synchronization platform)
WhyLabs (whylogs) - https://www.whylabs.ai/ - MLOps/Data AI (AI observability and data logging platform)
Wonder Dynamics (Wonder Studio) - https://wonderdynamics.com/ - Creative AI (AI for VFX & Animation)
Workato - https://workato.com/ - AI-Powered Automation (Enterprise-grade integration and automation platform with AI)
Workday (AI for HR/Finance) - https://www.workday.com/solutions/ai.html - HR/Finance AI (AI for talent acquisition, workforce analytics, financial forecasting)
Writer - https://writer.com/ - Enterprise AI (Enterprise AI software for content creation and governance)
Xero (AI features) - https://www.xero.com/ - AI-Powered Business Applications (Cloud-based accounting software with AI)
XOCEAN - https://www.xocean.com/ - Maritime AI (AI-powered uncrewed surface vessels for hydrographic surveys)
YouTube (AI for recommendations, Content ID, moderation) - https://www.youtube.com/ - Recommendation/Content Moderation AI (AI for video recommendations, content identification, comment moderation)
Zapier AI Integration - https://zapier.com/ai - AI-Powered Automation (Automates workflows by connecting different apps without coding)
ZenRobotics - https://zenrobotics.com/ - Waste Management AI (AI-powered robotic waste sorting systems)
Zeni AI - https://zeni.ai/ - Financial AI (AI for Bookkeeping & Finance Operations)
Zesty.ai - https://www.zesty.ai/ - Insurance AI (AI for property risk assessment from climate and natural disasters)
Zoho Desk (Answer Bot) - https://www.zoho.com/desk/ - Customer Service AI (Ticketing system with AI for customer support)
Zoho Zia (AI Assistant) - https://www.zoho.com/zia/ - Business AI (AI-powered assistant embedded across Zoho's suite)
Zoom (AI Companion) - https://www.zoom.us/ai-companion - Meeting AI (AI for meeting summaries, intelligent recordings, and real-time coaching)
Zumper (AI features) - https://www.zumper.com/ - Real Estate AI (AI for rental search and personalized recommendations)

Hyper-niche generative AI for specific artistic styles, media, or very granular content creation tasks.
AI for highly specialized hobbies, crafts, or scientific sub-disciplines.
AI tools that are emerging from research or are less formalized commercial offerings.
AI in advanced simulation and modeling for very specific engineering or scientific problems.

ps2ai.com (PS2 Filter AI) - https://ps2ai.com/ - Generative Art AI (AI for generating images in the style of PlayStation 2 graphics)
Retro Diffusion (by Runware) - https://runware.ai/blog/retro-diffusion-creating-authentic-pixel-art-with-ai-at-scale - Generative Art AI (AI for creating authentic pixel art with consistent grid alignment and color limitations)
ImagineArt AI Aesthetic Generator - https://www.imagine.art/features/ai-aesthetic-generator - Generative Art AI (AI for generating images based on specific aesthetic moods, themes, or styles)
AnimeDiffusion - (Often community-run or API-based, e.g., on Hugging Face) - Generative Art AI (AI models and tools specifically for generating anime-style art)
This Person Does Not Exist - https://thispersondoesnotexist.com/ - Generative Art AI (AI for generating photorealistic images of non-existent human faces)
This Cat Does Not Exist - https://thiscatdoesnotexist.com/ - Generative Art AI (AI for generating photorealistic images of non-existent cats)
TextFX (Google) - https://textfx.withgoogle.com/ - Generative Text AI (AI experimentation tool for generating creative text, e.g., similes, proverbs, plot outlines)
ElevenLabs (Voice Library & API) - https://elevenlabs.io/ - Voice AI (Advanced voice cloning and highly customizable speech synthesis via API, beyond standard text-to-speech)
D-ID (Creative Reality Studio) - https://www.d-id.com/ - Generative Video AI (AI for creating talking avatars from images or video, with text-to-speech)
Hour One - https://hourone.ai/ - Generative Video AI (AI for creating AI presenters and videos for enterprise communication)
Pictory AI - https://pictory.ai/ - Generative Video AI (AI for converting text, articles, or scripts into video summaries)

AI for Very Niche Scientific & Engineering Tools:

Exabyte.io - https://www.exabyte.io/ - Materials Science AI (Cloud platform for materials modeling and simulation with AI for property prediction)
Schrodinger (LiveDesign) - https://www.schrodinger.com/livedesign - Drug Discovery AI (AI-enabled computational platform for drug discovery collaboration)
Recursion Pharmaceuticals (Phenom-seq) - https://www.recursionpharma.com/platform/#phenom-seq - Biotech AI (AI-enabled functional genomics screening platform)
Enthought (Horizon) - https://www.enthought.com/platform/horizon - Scientific AI (AI platform for scientific data analysis and engineering R&D)
Heliogen - https://heliogen.com/ - Clean Energy AI (AI for optimizing concentrated solar power systems and energy generation)
QuantumBlack (McKinsey & Company) - https://www.mckinsey.com/capabilities/quantumblack/overview - AI Consulting/Solutions (Applies advanced AI to complex business problems, often building custom solutions as a service)
Acelab - https://acelab.ai/ - Construction AI (AI for material specification and product discovery in architecture & construction)
Carbon Chain - https://carbonchain.com/ - Supply Chain AI (AI for automated supply chain carbon emissions tracking and reporting)
Ardoq (AI Features) - https://www.ardoq.com/ai - Enterprise Architecture AI (AI for understanding and mapping complex enterprise IT landscapes)
Blue Vision Labs (acquired by Lyft) - (Service integrated into Lyft) - Environmental AI (AI for Real-time 3D Mapping for Smart Cities)
The Climate Corporation (FieldView) - https://climate.com/ - Agriculture/Environmental AI (AI for predictive insights on crop performance based on climate and field data)
SatSure - https://satsure.co/ - Geospatial AI (AI for satellite-based analytics for agriculture, banking, and climate insights)
Aquantix - https://aquantix.ai/ - Water Management AI (AI for water resource management, leak detection, and demand forecasting)
Picarro - https://www.picarro.com/ - Environmental AI (AI for high-precision gas analysis for greenhouse gas monitoring and leak detection)
Kayrros - https://www.kayrros.com/ - Environmental AI (AI for global energy and environmental intelligence, including methane emissions tracking)

AI for Niche Industrial & Automation Applications:

Instrument Systems (Luminance Pro AI) - https://www.instrumentsystems.com/en/products/light-measurement/luminance-and-color-measurement-cameras/luminance-pro-ai/ - Industrial AI (AI for optical quality control in displays and light sources)
Cognex (VisionPro Deep Learning) - https://www.cognex.com/products/deep-learning - Industrial AI (AI for complex defect detection and optical character recognition in manufacturing)
Vanti Analytics - https://www.vantianalytics.com/ - Industrial AI (AI for predictive quality and root cause analysis in manufacturing)
Landing.ai (LandingLens) - https://landing.ai/landinglens/ - Industrial AI (Computer Vision platform for visual inspection in manufacturing)
Covariant.ai - https://covariant.ai/ - Robotics AI (AI for robotic manipulation in warehouses and fulfillment centers)
RightHand Robotics - https://www.righthandrobotics.com/ - Robotics AI (AI for robotic piece-picking in logistics and e-commerce)
Symbio Robotics (SymbioDCS) - https://symbiorobotics.com/ - Robotics AI (AI for industrial robot programming and optimization)
ZenRobotics - https://zenrobotics.com/ - Waste Management AI (AI-powered robotic waste sorting systems)
Recycleye - https://www.recycleye.com/ - Waste Management AI (AI & Robotics for Waste Classification and Sorting)
AMP Robotics - https://www.amprobotics.com/ - Waste Management AI (AI-powered robotics for material recovery facilities)
Greyparrot - https://greyparrot.ai/ - Waste Management AI (AI-powered waste analysis platform)
Urbint - https://www.urbint.com/ - Infrastructure AI (AI for predicting infrastructure risk and optimizing operations for utilities)
Sense (Home Energy AI) - https://sense.com/ - Home Energy AI (AI for home energy monitoring and insights)
Span.IO (AI features) - https://www.span.io/ - Home Energy AI (Smart electrical panel with AI for energy management)
Moixa - https://www.moixa.com/ - Energy Storage AI (AI for optimizing battery storage and smart charging)

AI for Very Specific Data & MLOps Tasks:
Tamr - https://www.tamr.com/ - Data Unification AI (AI for data mastering, cleaning, and unification from disparate sources)
BigID - https://bigid.com/ - Data Privacy AI (AI for discovering, classifying, and protecting sensitive data for privacy compliance)
Monte Carlo - https://www.montecarlodata.com/ - Data Observability AI (AI for data reliability, monitoring data quality, and anomaly detection)
Datafold - https://datafold.com/ - Data Observability AI (AI for data testing, lineage, and observability in data pipelines)
Anomalo - https://www.anomalo.com/ - Data Quality AI (AI for automated data quality monitoring and anomaly detection)
WhyLabs (whylogs) - https://www.whylabs.ai/ - MLOps/Data AI (AI observability and data logging platform)
CausaLens - https://causalens.com/ - Explainable AI (XAI) (AI platform for causal AI)

AI for Niche Business & Public Sector Solutions:
ChowNow (OrderBetter AI) - https://orderbetter.ai/ - Food Service AI (AI for optimizing online ordering and delivery for restaurants)
Toast (AI-powered scheduling) - https://pos.toasttab.com/restaurant-management/schedules - Food Service AI (AI for restaurant staff scheduling optimization)
Pendo (AI features) - https://www.pendo.io/platform/ai/ - Product Analytics AI (AI for product usage insights and user behavior analytics)
Amplitude (AI features) - https://amplitude.com/solutions/ai-for-product - Product Analytics AI (AI for product analytics and growth insights)
Mixpanel (AI features) - https://mixpanel.com/solutions/ai-for-product-analytics/ - Product Analytics AI (AI for user behavior analysis and product decision making)
Kore.ai - https://kore.ai/ - Conversational AI (Enterprise conversational AI platform for virtual assistants and process automation)
Civitas (AI for Government) - https://www.civitas.ai/ - Public Sector AI (AI for government data analysis and civic engagement)
Polis - https://pol.is/ - Social AI (AI for identifying consensus and divisive topics in large-scale online conversations)
AI.builders - https://ai.builders/ - Construction AI (AI for automating construction planning, scheduling, and risk assessment)
Unspun (FitOS) - https://unspun.io/ - Retail AI (AI for personalized clothing sizing and custom production)
Daydream - https://daydream.shop/ - Retail AI (AI Chat-to-Shop for personalized fashion discovery)
PredictNow.ai - https://www.predictnow.ai/ - Financial AI (Hedge Fund Investment AI for predictive analytics)
Fathom AI - https://fathom.fm/ - AI for Meetings (AI Notetaker & Summarizer for virtual meetings)
Rephrase.ai - https://rephrase.ai/ - Generative Video AI (AI for personalized video creation using synthetic media)
Fireflies.ai - https://fireflies.ai/ - Meeting AI (AI for transcribing, summarizing, and analyzing voice conversations from meetings)
Grain.com - https://grain.com/ - Meeting AI (AI for recording, transcribing, and sharing key moments from video meetings)
Truepic - https://www.truepic.com/ - Authenticity AI (AI for image and video authentication, combating deepfakes and manipulated media)
Lexion - https://www.lexion.ai/ - Legal AI (AI for contract management and legal agreement analysis)
LegalZoom (AI features) - https://www.legalzoom.com/ - Legal AI (AI for guiding users through legal document creation and business formation)
Everlaw (AI Assistant) - https://www.everlaw.com/ - Legal AI (AI for eDiscovery review and litigation support)
Workera - https://www.workera.ai/ - Workforce AI (AI for skill assessment, development, and talent strategy)
Retrain.ai - https://www.retrain.ai/ - Workforce AI (AI for workforce intelligence, skill identification, and talent mobility)
"""

    parsed_json = parse_ai_services(input_text)
    with open("parsed_services.json", "w") as f:
        f.write(parsed_json)
    print("Parsing complete. Output written to parsed_services.json")
